apiVersion: v1
kind: Service
metadata:
  name: online-shop
  namespace: online-shop-prod
  labels:
    app: online-shop
spec:
  type: LoadBalancer
  selector:
    app: online-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
